### ISSUE TITLE
Killer Cog - V3.5 Update required

### ISSUE THREAD

**Issue by Khapra** [designbyadrian/CogsByAdrian#6]
[2023-05-09 09:19:17] [WARNING] py.warnings: /data/cogs/CogManager/cogs/killer/__init__.py:4: RuntimeWarning: coroutine 'Red.add_cog' was never awaited
  bot.add_cog(Killer())

[2023-05-09 09:19:17] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "/data/venv/lib/python3.9/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "/data/venv/lib/python3.9/site-packages/redbot/core/bot.py", line 1686, in load_extension
    await lib.setup(self)
TypeError: object NoneType can't be used in 'await' expression

**Comment by Khapra** [comment]
same issue for the Penis Cog.

**Comment by designbyadrian** [comment]
Sorted the four cogs in this collection! Thank you for your report.
